FROM ruby:3.2.2-slim

# Install dependencies
RUN apt-get update -qq && apt-get install -y nodejs npm
RUN npm install --global yarn

# Install dependencies
RUN apt-get update -qq && apt-get install -y \
    build-essential \
    default-libmysqlclient-dev \
    nodejs \
    netcat-openbsd \
    git \
    && rm -rf /var/lib/apt/lists/*

# Set working directory
WORKDIR /rails

# Install gems
COPY Gemfile Gemfile.lock ./
RUN bundle install

# Copy application code
COPY . .

# Expose port
EXPOSE 3000

# Start server  
CMD ["bundle", "exec", "rails", "server", "-b", "0.0.0.0"]